version: '3.7'

services:
  site:
    build: ./
    volumes:
      - ./site:/var/www/html
    ports:
      - "8082:80"

  nginx:
    image: nginx
    volumes:
      - ./site:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - NGINX_PORT=80
    ports:
      - 80:80
    depends_on:
      - site      
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3307:3306"
    volumes:
      - "./initdb:/docker-entrypoint-initdb.d"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8000:80
    environment:
      - VIRTUAL_HOST=phpmyadmin.local
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=password
    depends_on:
      - db